version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.4-jessie-browsers
    steps:
      - checkout
      - run:
          name: 'Setup'
          command: |
            virtualenv -p python3 ~/.virtualenvs/tap-shippo
            source ~/.virtualenvs/tap-shippo/bin/activate
            pip install .
            pip install pylint
      - run:
          name: 'Pylint'
          command: |
            source ~/.virtualenvs/tap-shippo/bin/activate
            pylint tap_shippo -r n -d missing-docstring,locally-disabled
